### ISSUE TITLE
Error with LowParse.Low.VLGen.fst

### ISSUE THREAD

**Issue by gliech27** [project-everest/everparse#10]
When I run the make command I get this error:
`LowParse.Low.VLGen.fst(457,2-468,46): (Error 16) Unknown assertion failed; Try with --query_stats to get more details
Verified module: LowParse.Low.VLGen
1 error was reported (see above)`

Here's the output when I use --query_stats:
`LowParse.Low.VLGen.fst(457,2-468,46): (Error 16) Unknown assertion failed
	SMT solver says:
	unknown because canceled (fuel=8; ifuel=2);
	unknown because canceled (fuel=4; ifuel=2);
	unknown because unknown (fuel=2; ifuel=2);
	unknown because canceled (fuel=2; ifuel=1);
	Note: 'canceled' or 'resource limits reached' means the SMT query timed out, so you might want to increase the rlimit;
	'incomplete quantifiers' means a (partial) counterexample was found, so try to spell your proof out in greater detail, increase fuel or ifuel
	'unknown' means Z3 provided no further reason for the proof failing
Verified module: LowParse.Low.VLGen
1 error was reported (see above)`

**Comment by tahina-pro** [comment]
Thanks for reporting. Yes, this file has among the least stable F* proofs, sensitive to any small change in F* that impacts Z3 heuristics. We do have a more-often-than-daily CI that checks that this proof goes through with the latest F* `master`.

**Comment by tahina-pro** [comment]
The CI badges are now appearing in the README.
