### ISSUE TITLE
RFC Parsing Error

### ISSUE THREAD

**Issue by prpr2770** [project-everest/everparse#11]
While compiling the following RFC, there's a parsing error which is detected at the definition of Object o1 when the assigned values are represented as ENUM tags. However, Object 02's definition using integers does not present any parsing errors. 
```
enum {
  REJECT(1),
  IGNORE(2),
  NOTIFY(3),
  (7)
 } Criticality;

 enum {
  OPTIONAL(1),
  CONDITIONAL(2),
  MANDATORY(3),
  (7)
 } Presence;

enum{
	BANANA,
	APPLE
}Fruit; 

struct{
	uint8 number; 
}V1; 

struct{
	uint16 number; 
}V2;

 struct{
 	Criticality 	criticality;
 	Presence 		presence; 
 	Fruit 			fruit;
 	select(fruit){
 	case BANANA: 	V1; 
 	case APPLE: 	V2;
 	}fruit_body;

 }Object;

Object o1 = {Criticality.REJECT, Presence.OPTIONAL, Fruit.BANANA};

Object o2 = {1, 1, 1};
```

The parsing error that's generated isn't very informative. 

> ("Object")
("o1")
13
9
("Criticality.REJECT")
Parsing error near ./test.rfc(40,13)-./test.rfc(40,31)

**Comment by ad-l** [comment]
Hi, there is currently no support in QD for creating instances of a defined datatype.
You need to do that in F* or in C, e.g.
```C
#include "Object.h"
#include "Criticality.h"
#include "Presence.h"
#include "Fruit.h"
#include "Object_fruit_body.h"

Object_object o1 = {
  .criticality = Criticality_REJECT,
  .presence = Presence_OPTIONAL,
  .fruit_body = {
    .fruit = Fruit_BANANA,
    { .case_BANANA = (uint8_t) 0 }
  }
};
```
