### ISSUE TITLE
Finding quackyducky

### ISSUE THREAD

**Issue by achamayou** [project-everest/everparse#12]
When using the docker container to get started with quackyducky, the path suggested in the README.md does not exist: https://github.com/project-everest/everparse/blob/master/README.md#running

Instead, the binary lives at `quackyducky/_build/src/quackyducky.native`. Could either the README or the CI producing the images be amended to make finding the binary easier?

**Comment by tahina-pro** [comment]
Thanks for reporting. I am amending the README to point to `./qd` , which is a symlink to that binary.

**Comment by achamayou** [comment]
@tahina-pro thank you!
