### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by achamayou** [project-everest/everparse#13]
Using the docker image to get a recent quacky ducky build is convenient, but it would be even more convenient to have binary packages with the executable for two reasons:

1. They'd presumably persist for a very long time, whereas the containers get cleaned up frequently. Users who are interested in reproducible builds (of what they build with quackyducky) will be nervous about using an evergreen container.
2. They'd be smaller. As far as I can tell, the binary is only about 6Mb, and seem to be completely statically linked. The 5.5Gb container takes a long time to download, it's a bit awkward for CI usage for example.

Are there obstacles to packaging the binary that I haven't spotted?

**Comment by tahina-pro** [comment]
For internal purposes, we do produce Windows binary packages for the `everparse_3d` branch. Those appear under the releases tab. Those binary packages are standalone, as they contain z3, F* and KReMLin. Such a package still totals more than 100 MB, but yes, I agree that it is much more stable than a Evergreen Docker container.

Currently, these packages are produced independently of the F* binary packages. Ideally we should streamline the process and produce binary packages that can depend on one another (i.e. we should produce KReMLin binary packages that build on top of the existing F* binary packages, and EverParse packages that build on top of KReMLin packages.)

**Comment by achamayou** [comment]
@tahina-pro I hadn’t seen those, they look very convenient and should be mentioned in the README. What’s the process used to produce those releases, could it be extended to Linux?

**Comment by tahina-pro** [comment]
Those releases are produced mostly manually:
1. We first tag our release.
2. Then, we run `make package`, which automatically builds F*, KReMLin, EverParse and bundles everything into a .zip file.
3. Then, we manually upload this .zip file to the release.

So far I have focused on producing a Windows binary package because of a/ our current internal users; b/ the Windows peculiarities, mostly the .dll needed by Z3, F*, etc. so that all binary executables have to be in the same directory. Then I have a Windows-specific .bat driver that sets up environment variables and calls into those executables.

On Linux, I by far don't expect anything as complex, although environment variables will still be relevant.

**Comment by tahina-pro** [comment]
I forgot to mention that this Windows binary package is completely standalone, i.e. it does not need Cygwin, OCaml, or anything like that.

**Comment by tahina-pro** [comment]
EverParse/3d (branch `everparse_3d`) now has both Linux and Windows binary packages, see https://github.com/project-everest/everparse/releases/tag/v2020.06.14
They are now documented accordingly at http://project-everest.github.io/everparse

**Comment by tahina-pro** [comment]
It now remains to produce binary packages for `master` , i.e. QuackyDucky. The main differences between QuackyDucky and 3d wrt. a potential binary package:
* whereas 3d goes all the way down to producing `.c` and `.h` files, QuackyDucky only produces `.fst` and `.fsti` files
* the dependency tree of the files produced by Quackyducky is nontrivial

**Comment by achamayou** [comment]
@tahina-pro that’s great, sorry if it’s a silly question but what is 3d?

**Comment by tahina-pro** [comment]
3d means "Dependent Data Descriptions." It is a data description language documented at https://project-everest.github.io/everparse/3d-lang.html , that @nikswamy and I are developing, along with a frontend, part of EverParse, documented at https://project-everest.github.io/everparse/3d.html, that generates verified validators from 3d data format descriptions. 3d is an alternative to QuackyDucky; both compile to F* code using LowParse combinators.

**Comment by tahina-pro** [comment]
QuackyDucky is now also part of EverParse binary releases.
