### ISSUE TITLE
c3d: small issues, a list

### ISSUE THREAD

**Issue by msprotz** [project-everest/everparse#30]
testing:
- [ ] test suite to compare input .h and output .3d and output .preprocessed.h (`diff -w` non-zero = failure)
- [ ] warn if clang-format is not a no-op

build:
- [x] figure out how to make this a standalone tool
- [ ] figure out how to make this a *windows* standalone tool

source code fidelity:
- [x] figure out how to retain SAL annotations in the preprocessed header, possibly using a macro to encode them as an annotation when going through c3d (?), or a semantic comment (?)
- [x] figure out how to retain UINTXX types (à la Windows) in the preprocessed header, is this covered by `-fms-extensions (?)`, otherwise put some typedefs behind a `#if defined(__clang__)`?

Note: these two can be solved in one go by getting the rewriting buffer to work, which would allow preserving the source exactly as-is. This would also alleviate the need for users to customize their source code with #defines, as these could be grouped into a separate header that gets included via -include. The rewriting buffer code currently segfaults, I need to understand why. **Update: done by Jonathan**

- [ ] use the cursor API for more precise placement of comments

usability:
- [ ] start working on error messages, see for instance error recovery for trailing commas in argument payload, or missing argument payload
- [ ] allow decorating structs that are in a top-level C++ namespace (low-priority)
- [ ] error if a field has an `everparse::_` attribute without `everparse::process` on its top-level declaration
- [ ] generally, aim for the invariant that if c3d accepts a file, then 3d will accept it too

new clang patch:
- [ ] expose parsing of a spec-and-decl
- [ ] expose parsing of an exprstmt for actions

engineering:
- [ ] lots of repeated parsing code, any way to avoid duplication, e.g. a template to parse something properly wrapped in parentheses?

features:
- [ ] support for arrays; `uint32_t x[4];` translates to `uint32_t x {:byte-size 4 * sizeof uint32_t }`
- [ ] support for all formats of byte sizes (see manual)
- [ ] composition of arrays with application of arguments via `everparse::with`
- [ ] actions
- [ ] recognize struct _FOO and add FOO, *PFOO as part of the typedef
- [ ] deal with padding, emit "aligned" unless #pragma pack is present
- [ ] automatically emit refines predicates to check 3d against C structs

tidbits:
- [ ] missing error checks on `C3dVisitor`

**Comment by nikswamy** [comment]
We are no longer working on c3d; closing.
